import {
  ADASModel, ExpectationsPhillipsModel, FiscalDebtModel, GoodsMarketModel, ISLMEngine,
  LaborMarketModel, linspace, MoneyMarketModel, MonetaryTransmissionModel, MundellFlemingModel,
  runPolicyScenario, SolowModel, TaylorRuleModel
} from './models';
import type { Lang, ModelState } from '../data/registry';

export type Metric = { label: string; value: string; delta?: string };
export type ChartSpec = { title: string; data: any[]; layout?: Record<string, any> };
export type DataTable = { columns: string[]; rows: (string | number)[][] };
export type ModelView = { metrics: Metric[]; charts: ChartSpec[]; analysis: string; formula: string; table: DataTable; warning?: string };

const n = (x: unknown) => Number(x);
const s = (x: unknown) => String(x);
const b = (x: unknown) => Boolean(x);
const pct = (x: number, d=2) => `${(100*x).toFixed(d)}%`;
const pp = (x: number, d=2) => `${(100*x)>=0?'+':''}${(100*x).toFixed(d)} pp`;
const num = (x: number, d=2) => x.toLocaleString(undefined,{maximumFractionDigits:d,minimumFractionDigits:d});
const delta = (x: number,d=2,suffix='') => `${x>=0?'+':''}${x.toFixed(d)}${suffix}`;
const commonLayout = (lang: Lang, xTitle: string, yTitle: string) => ({
  autosize:true, margin:{l:58,r:22,t:28,b:50}, paper_bgcolor:'transparent', plot_bgcolor:'transparent',
  font:{family:'Inter, Vazirmatn, system-ui, sans-serif', color:'#dbeafe'},
  legend:{orientation:'h', y:-.2}, hovermode:'closest',
  xaxis:{title:xTitle,gridcolor:'rgba(148,163,184,.13)',zerolinecolor:'rgba(148,163,184,.25)'},
  yaxis:{title:yTitle,gridcolor:'rgba(148,163,184,.13)',zerolinecolor:'rgba(148,163,184,.25)'},
  direction:lang==='fa'?'rtl':'ltr'
});
const baseLine = {color:'#64748b',width:2,dash:'dot'};
const blue = {color:'#38bdf8',width:3};
const red = {color:'#fb7185',width:3};
const green = {color:'#34d399',width:3};
const amber = {color:'#fbbf24',width:3};

export function buildModelView(id: string, current: ModelState, base: ModelState, lang: Lang): ModelView {
  const fa = lang === 'fa';
  try {
    if (id === 'goods') {
      const bm = new GoodsMarketModel({c0:n(base.c0),mpc:n(base.mpc),t:n(base.tax),G:n(base.G)});
      const cm = new GoodsMarketModel({c0:n(current.c0),mpc:n(current.mpc),t:n(current.tax),G:n(current.G)});
      const r0=n(base.r), r1=n(current.r), y0=bm.solveEquilibriumOutput(r0), y1=cm.solveEquilibriumOutput(r1);
      const lo=Math.max(0,Math.min(y0,y1)*.45), hi=Math.max(Math.max(y0,y1)*1.45,lo+500), Y=linspace(lo,hi,240);
      const cross:any[]=[
        {x:Y,y:Y,type:'scatter',mode:'lines',name:'45°',line:{color:'#94a3b8',dash:'dash'}},
        {x:Y,y:Y.map(v=>bm.plannedExpenditure(v,r0)),type:'scatter',mode:'lines',name:fa?'مخارج مبنا':'Baseline Z',line:baseLine},
        {x:Y,y:Y.map(v=>cm.plannedExpenditure(v,r1)),type:'scatter',mode:'lines',name:fa?'مخارج جاری':'Current Z',line:blue},
        {x:[y0],y:[y0],type:'scatter',mode:'markers+text',text:['E₀'],textposition:'top left',name:'E₀',marker:{size:9,color:'#94a3b8'}},
        {x:[y1],y:[y1],type:'scatter',mode:'markers+text',text:['E₁'],textposition:'top left',name:'E₁',marker:{size:12,color:'#f8fafc'}},
      ];
      if(b(current.showPath) && Math.abs(y1-y0)>1){const p=cm.inventoryPath(r1,y0);cross.push({x:p.x,y:p.y,type:'scatter',mode:'lines+markers',name:fa?'مسیر تعدیل':'Adjustment path',line:green,marker:{size:4}})}
      const isData=[
        {x:Y,y:Y.map(v=>bm.isCurveRate(v)),type:'scatter',mode:'lines',name:fa?'IS مبنا':'Baseline IS',line:baseLine},
        {x:Y,y:Y.map(v=>cm.isCurveRate(v)),type:'scatter',mode:'lines',name:fa?'IS جاری':'Current IS',line:red},
        {x:[y0,y1],y:[r0,r1],type:'scatter',mode:'markers+text',text:['E₀','E₁'],textposition:'top right',name:fa?'تعادل':'Equilibrium',marker:{size:[9,12],color:['#94a3b8','#f8fafc']}}
      ];
      return {metrics:[{label:'Y*',value:num(y1,1),delta:delta(y1-y0,1)},{label:fa?'ضریب فزاینده':'Multiplier',value:num(cm.multiplier,2),delta:delta(cm.multiplier-bm.multiplier,2)},{label:'I',value:num(cm.investment(r1),1),delta:delta(cm.investment(r1)-bm.investment(r0),1)},{label:'r',value:pct(r1),delta:pp(r1-r0)}],charts:[{title:fa?'تقاطع کینزی':'Keynesian Cross',data:cross,layout:commonLayout(lang,'Y','Z')},{title:fa?'استخراج منحنی IS':'IS Curve',data:isData,layout:{...commonLayout(lang,'Y','r'),yaxis:{...commonLayout(lang,'Y','r').yaxis,tickformat:'.1%'}}}],analysis:fa?`در وضعیت جاری، تولید تعادلی ${num(y1,1)} است. تغییر نسبت به مبنا ${delta(y1-y0,1)} واحد است. ضریب فزاینده برابر ${num(cm.multiplier,2)} است و تغییرات G، مالیات یا نرخ بهره از مسیر مخارج خودمختار و شیب مخارج برنامه‌ریزی‌شده به تعادل منتقل می‌شوند.`:`Current equilibrium output is ${num(y1,1)}, a change of ${delta(y1-y0,1)} from baseline. The multiplier is ${num(cm.multiplier,2)}; G, taxes and interest rates work through autonomous spending and planned expenditure.`,formula:`Y = [c₀ + i₀ − b·r + G] / [1 − MPC(1−t)]\nIS: r = (c₀+i₀+G)/b − [1−MPC(1−t)]Y/b`,table:{columns:[fa?'متغیر':'Variable',fa?'مبنا':'Baseline',fa?'جاری':'Current',fa?'تغییر':'Change'],rows:[['Y*',y0,y1,y1-y0],['Multiplier',bm.multiplier,cm.multiplier,cm.multiplier-bm.multiplier],['Investment',bm.investment(r0),cm.investment(r1),cm.investment(r1)-bm.investment(r0)],['r',r0,r1,r1-r0]]}};
    }

    if (id === 'money') {
      const bm=new MoneyMarketModel({M:n(base.M),P:n(base.P),k:n(base.k),h:n(base.h),rFloor:n(base.rFloor),regime:s(base.regime) as any});
      const cm=new MoneyMarketModel({M:n(current.M),P:n(current.P),k:n(current.k),h:n(current.h),rFloor:n(current.rFloor),regime:s(current.regime) as any});
      const Y0=n(base.Y),Y1=n(current.Y),r0=bm.solveEquilibriumRate(Y0),r1=cm.solveEquilibriumRate(Y1);
      const candidates=[bm.realMoneySupply,cm.realMoneySupply,bm.k*Y0,cm.k*Y1]; const lo=Math.max(0,Math.min(...candidates)-180),hi=Math.max(...candidates)+220,x=linspace(lo,hi,260);
      const data:any[]=[];
      const add=(m:MoneyMarketModel,Y:number,name:string,line:any)=>{if(m.regime==='classical'){const xc=m.k*Y;data.push({x:[xc,xc],y:[-.04,.18],type:'scatter',mode:'lines',name,line})}else data.push({x,y:x.map(v=>m.inverseMoneyDemand(v,Y)),type:'scatter',mode:'lines',name,line}); data.push({x:[m.realMoneySupply,m.realMoneySupply],y:[-.04,.18],type:'scatter',mode:'lines',name:`${name} MS`,line:{...line,dash:'dash'}})};
      add(bm,Y0,fa?'مبنا':'Baseline',baseLine);add(cm,Y1,fa?'جاری':'Current',blue);
      if(Number.isFinite(r0)) data.push({x:[bm.realMoneySupply],y:[r0],type:'scatter',mode:'markers+text',text:['E₀'],textposition:'top right',marker:{size:9,color:'#94a3b8'},name:'E₀'});
      if(Number.isFinite(r1)) data.push({x:[cm.realMoneySupply],y:[r1],type:'scatter',mode:'markers+text',text:['E₁'],textposition:'top left',marker:{size:12,color:'#f8fafc'},name:'E₁'});
      const rateLabel=Number.isFinite(r1)?pct(r1):fa?'تعیین‌نشده در حالت کلاسیک':'Indeterminate in classical case';
      return {metrics:[{label:'M/P',value:num(cm.realMoneySupply,1),delta:delta(cm.realMoneySupply-bm.realMoneySupply,1)},{label:'r*',value:rateLabel,delta:Number.isFinite(r0)&&Number.isFinite(r1)?pp(r1-r0):''},{label:'Y',value:num(Y1,0),delta:delta(Y1-Y0,0)},{label:fa?'رژیم':'Regime',value:cm.regime}],charts:[{title:fa?'بازار پول':'Money Market',data,layout:{...commonLayout(lang,'M/P','r'),yaxis:{...commonLayout(lang,'M/P','r').yaxis,tickformat:'.1%'}}}],analysis:fa?`عرضه حقیقی پول ${num(cm.realMoneySupply,1)} است. ${cm.regime==='liquidity_trap'?'کف نرخ بهره باعث ایجاد شاخه دام نقدینگی می‌شود.':cm.regime==='classical'?'در حالت کلاسیک، تقاضای پول نسبت به نرخ بهره واکنش نشان نمی‌دهد و LM عمودی می‌شود.':'در حالت استاندارد، تعادل از تقاطع عرضه حقیقی پول و تقاضای پول به دست می‌آید.'}`:`Real money balances are ${num(cm.realMoneySupply,1)}. ${cm.regime==='liquidity_trap'?'The interest-rate floor creates a liquidity-trap branch.':cm.regime==='classical'?'In the classical case money demand is interest-inelastic and LM is vertical.':'In the standard case equilibrium is the intersection of real money supply and money demand.'}`,formula:`M/P = kY − hr\nr = (kY − M/P)/h`,table:{columns:['Variable','Baseline','Current','Change'],rows:[['M/P',bm.realMoneySupply,cm.realMoneySupply,cm.realMoneySupply-bm.realMoneySupply],['Y',Y0,Y1,Y1-Y0],['r',r0,r1,Number.isFinite(r0)&&Number.isFinite(r1)?r1-r0:NaN]]}};
    }

    if (id === 'islm') {
      const make=(v:ModelState)=>new ISLMEngine({G:n(v.G),t:n(v.tax),M:n(v.M),P:n(v.P),rFloor:n(v.rFloor),regime:s(v.regime) as any});
      const bm=make(base),cm=make(current),e0=bm.solveEquilibrium(),e1=cm.solveEquilibrium(); const center=(e0.Y+e1.Y)/2,lo=Math.max(0,center-500),hi=Math.max(1300,center+500),Y=linspace(lo,hi,320);
      const data:any[]=[{x:Y,y:Y.map(v=>bm.isCurve(v)),type:'scatter',mode:'lines',name:fa?'IS مبنا':'Baseline IS',line:baseLine}];
      if(bm.regime==='classical'){const yy=bm.realMoneySupply/bm.k;data.push({x:[yy,yy],y:[-.08,.20],type:'scatter',mode:'lines',name:fa?'LM کلاسیک مبنا':'Baseline classical LM',line:baseLine})}else data.push({x:Y,y:Y.map(v=>bm.lmCurve(v)),type:'scatter',mode:'lines',name:fa?'LM مبنا':'Baseline LM',line:baseLine});
      data.push({x:Y,y:Y.map(v=>cm.isCurve(v)),type:'scatter',mode:'lines',name:'IS',line:red});
      if(cm.regime==='classical'){const yy=cm.realMoneySupply/cm.k;data.push({x:[yy,yy],y:[-.08,.20],type:'scatter',mode:'lines',name:fa?'LM کلاسیک':'Classical LM',line:blue})}else data.push({x:Y,y:Y.map(v=>cm.lmCurve(v)),type:'scatter',mode:'lines',name:'LM',line:blue});
      data.push({x:[e0.Y,e1.Y],y:[e0.r,e1.r],type:'scatter',mode:'markers+text',text:['E₀','E₁'],textposition:'top right',marker:{size:[9,12],color:['#94a3b8','#f8fafc']},name:fa?'تعادل':'Equilibrium'});
      return {metrics:[{label:'Y*',value:num(e1.Y,1),delta:delta(e1.Y-e0.Y,1)},{label:'r*',value:pct(e1.r),delta:pp(e1.r-e0.r)},{label:'I',value:num(e1.I,1),delta:delta(e1.I-e0.I,1)},{label:fa?'تراز بودجه':'G−T',value:num(e1.Deficit,1),delta:delta(e1.Deficit-e0.Deficit,1)}],charts:[{title:'IS–LM',data,layout:{...commonLayout(lang,'Y','r'),yaxis:{...commonLayout(lang,'Y','r').yaxis,tickformat:'.1%'}}}],analysis:fa?`تعادل جاری در Y=${num(e1.Y,1)} و r=${pct(e1.r)} قرار دارد. تغییر نرخ بهره باعث تغییر سرمایه‌گذاری به ${num(e1.I,1)} شده است. رژیم LM جاری «${cm.regime}» است.`:`Current equilibrium is Y=${num(e1.Y,1)} and r=${pct(e1.r)}. The interest-rate change moves investment to ${num(e1.I,1)}. Current LM regime: ${cm.regime}.`,formula:`IS: Y = α(A − br)\nLM: M/P = kY − hr\nSolve simultaneously for Y and r.`,table:{columns:['Variable','Baseline','Current','Change'],rows:[['Y',e0.Y,e1.Y,e1.Y-e0.Y],['r',e0.r,e1.r,e1.r-e0.r],['C',e0.C,e1.C,e1.C-e0.C],['I',e0.I,e1.I,e1.I-e0.I],['G−T',e0.Deficit,e1.Deficit,e1.Deficit-e0.Deficit]]}};
    }

    if (id === 'adas') {
      const make=(v:ModelState)=>new ADASModel({A:n(v.A),M:n(v.M),costShock:n(v.z),PExpected:n(v.Pe),PPrevious:n(v.Pprev),lambdaSlope:n(v.lam)});
      const bm=make(base),cm=make(current),e0=bm.solveShortRunEquilibrium(),e1=cm.solveShortRunEquilibrium();
      const yc=(e0.Y+e1.Y+cm.YPotential)/3,ylo=Math.max(200,yc-550),yhi=Math.max(1500,yc+550);const plo=Math.max(.1,Math.min(e0.P,e1.P,cm.PExpected,cm.PPrevious)-.5),phi=Math.max(e0.P,e1.P,cm.PExpected,cm.PPrevious)+.7;const P=linspace(plo,phi,300),Y=linspace(ylo,yhi,300);
      const adas=[{x:bm===cm?[]:P.map(p=>bm.adOutput(p)),y:P,type:'scatter',mode:'lines',name:fa?'AD مبنا':'Baseline AD',line:baseLine},{x:P.map(p=>cm.adOutput(p)),y:P,type:'scatter',mode:'lines',name:'AD',line:blue},{x:Y,y:Y.map(y=>bm.srasPrice(y)),type:'scatter',mode:'lines',name:fa?'SRAS مبنا':'Baseline SRAS',line:baseLine},{x:Y,y:Y.map(y=>cm.srasPrice(y)),type:'scatter',mode:'lines',name:'SRAS',line:red},{x:[cm.YPotential,cm.YPotential],y:[plo,phi],type:'scatter',mode:'lines',name:'LRAS',line:{color:'#34d399',dash:'dash',width:2}},{x:[e0.Y,e1.Y],y:[e0.P,e1.P],type:'scatter',mode:'markers+text',text:['E₀','E₁'],textposition:'top right',marker:{size:[9,12],color:['#94a3b8','#f8fafc']},name:fa?'تعادل':'Equilibrium'}];
      const lim=Math.max(12,Math.abs(e0.Output_Gap)*1.4,Math.abs(e1.Output_Gap)*1.4),gaps=linspace(-lim,lim,260); const pc=[{x:gaps,y:gaps.map(g=>bm.phillipsInflation(g)),type:'scatter',mode:'lines',name:fa?'فیلیپس مبنا':'Baseline Phillips',line:baseLine},{x:gaps,y:gaps.map(g=>cm.phillipsInflation(g)),type:'scatter',mode:'lines',name:fa?'فیلیپس جاری':'Current Phillips',line:amber},{x:[e1.Output_Gap],y:[e1.Inflation],type:'scatter',mode:'markers+text',text:['E₁'],textposition:'top right',marker:{size:12,color:'#f8fafc'},name:'E₁'}];
      return {metrics:[{label:'Y',value:num(e1.Y,1),delta:delta(e1.Y-e0.Y,1)},{label:'P',value:num(e1.P,3),delta:delta(e1.P-e0.P,3)},{label:fa?'شکاف تولید':'Output gap',value:`${e1.Output_Gap.toFixed(2)}%`,delta:`${delta(e1.Output_Gap-e0.Output_Gap,2)} pp`},{label:fa?'تورم':'Inflation',value:`${e1.Inflation.toFixed(2)}%`,delta:`${delta(e1.Inflation-e0.Inflation,2)} pp`}],charts:[{title:'AD–AS',data:adas,layout:commonLayout(lang,'Y','P')},{title:fa?'فیلیپس کوتاه‌مدت':'Short-Run Phillips',data:pc,layout:commonLayout(lang,fa?'شکاف تولید (%)':'Output gap (%)',fa?'تورم (%)':'Inflation (%)')}],analysis:fa?`تعادل کوتاه‌مدت در Y=${num(e1.Y,1)} و P=${num(e1.P,3)} است. شکاف تولید ${e1.Output_Gap.toFixed(2)}٪ و تورم دوره‌ای ${e1.Inflation.toFixed(2)}٪ است. شوک هزینه z مستقیماً SRAS را جابه‌جا می‌کند.`:`Short-run equilibrium is Y=${num(e1.Y,1)} and P=${num(e1.P,3)}. The output gap is ${e1.Output_Gap.toFixed(2)}% and period inflation is ${e1.Inflation.toFixed(2)}%. Cost shock z shifts SRAS directly.`,formula:`AD: Y = γ[A + (b/h)(M/P)]\nSRAS: P = Pᵉ + λ(Y−Ȳ) + z`,table:{columns:['Variable','Baseline','Current','Change'],rows:[['Y',e0.Y,e1.Y,e1.Y-e0.Y],['P',e0.P,e1.P,e1.P-e0.P],['Output gap (%)',e0.Output_Gap,e1.Output_Gap,e1.Output_Gap-e0.Output_Gap],['Inflation (%)',e0.Inflation,e1.Inflation,e1.Inflation-e0.Inflation]]}};
    }

    if (id === 'open') {
      const make=(v:ModelState)=>new MundellFlemingModel({regime:s(v.regime) as any,G:n(v.G),M:n(v.M),rForeign:n(v.rf),YForeign:n(v.Yf),exchangeRate:n(v.epeg)});
      const bm=make(base),cm=make(current),e0=bm.solveEquilibrium(),e1=cm.solveEquilibrium();const center=(e0.Y+e1.Y)/2,lo=Math.max(100,center-600),hi=Math.max(1500,center+600),Y=linspace(lo,hi,300);
      const data=[{x:Y,y:Y.map(v=>bm.isCurve(v,e0.e)),type:'scatter',mode:'lines',name:fa?'IS مبنا':'Baseline IS',line:baseLine},{x:Y,y:Y.map(v=>bm.lmCurve(v,e0.M)),type:'scatter',mode:'lines',name:fa?'LM مبنا':'Baseline LM',line:baseLine},{x:Y,y:Y.map(v=>cm.isCurve(v,e1.e)),type:'scatter',mode:'lines',name:'IS',line:red},{x:Y,y:Y.map(v=>cm.lmCurve(v,e1.M)),type:'scatter',mode:'lines',name:'LM',line:blue},{x:[lo,hi],y:[cm.rForeign,cm.rForeign],type:'scatter',mode:'lines',name:'r = r*',line:green},{x:[e0.Y,e1.Y],y:[e0.r,e1.r],type:'scatter',mode:'markers+text',text:['E₀','E₁'],textposition:'top right',marker:{size:[9,12],color:['#94a3b8','#f8fafc']},name:fa?'تعادل':'Equilibrium'}];
      return {metrics:[{label:'Y',value:num(e1.Y,1),delta:delta(e1.Y-e0.Y,1)},{label:'r*',value:pct(e1.r),delta:pp(e1.r-e0.r)},{label:'e',value:num(e1.e,3),delta:delta(e1.e-e0.e,3)},{label:'NX',value:num(e1.NX,1),delta:delta(e1.NX-e0.NX,1)}],charts:[{title:fa?'ماندل–فلمینگ':'Mundell–Fleming',data,layout:{...commonLayout(lang,'Y','r'),yaxis:{...commonLayout(lang,'Y','r').yaxis,tickformat:'.1%'}}}],analysis:fa?`در اقتصاد کوچک باز با تحرک کامل سرمایه، نرخ بهره داخلی به r* متصل است. در رژیم ${cm.regime==='floating'?'شناور، نرخ ارز':'ثابت، عرضه پول'} متغیر تعدیل‌کننده است. تعادل جاری Y=${num(e1.Y,1)} و e=${num(e1.e,3)} است.`:`With perfect capital mobility, the domestic interest rate is tied to r*. Under ${cm.regime==='floating'?'floating FX, the exchange rate':'fixed FX, the money supply'} adjusts. Current Y=${num(e1.Y,1)}, e=${num(e1.e,3)}.`,formula:`r = r*\nIS*: Y = α_open[A(e) − br*]\nLM: M/P = kY − hr*`,table:{columns:['Variable','Baseline','Current','Change'],rows:[['Y',e0.Y,e1.Y,e1.Y-e0.Y],['e',e0.e,e1.e,e1.e-e0.e],['M equilibrium',e0.M,e1.M,e1.M-e0.M],['NX',e0.NX,e1.NX,e1.NX-e0.NX]]},warning:!e1.feasible?(fa?'این پارامترها به مرز امکان‌پذیری مدل نزدیک شده‌اند.':'Selected parameters are near/outside the model feasibility region.'):undefined};
    }

    if (id === 'solow') {
      const make=(v:ModelState)=>new SolowModel({s:n(v.s),A:n(v.A),alpha:n(v.alpha),delta:n(v.delta),n:n(v.n),g:n(v.g)});const bm=make(base),cm=make(current),s0=bm.solveSteadyState(),s1=cm.solveSteadyState();const kmax=Math.max(s0.k_star,s1.k_star,s1.k_gold,10)*1.55,k=linspace(.01,kmax,300);
      const steady=[{x:k,y:k.map(v=>cm.production(v)),type:'scatter',mode:'lines',name:'f(k)',line:blue},{x:k,y:k.map(v=>cm.savings(v)),type:'scatter',mode:'lines',name:'s f(k)',line:green},{x:k,y:k.map(v=>cm.breakEvenInvestment(v)),type:'scatter',mode:'lines',name:'(δ+n+g)k',line:red},{x:[s1.k_star],y:[s1.i_star],type:'scatter',mode:'markers+text',text:['k*'],textposition:'top right',marker:{size:12,color:'#f8fafc'},name:'k*'},{x:[s1.k_gold],y:[cm.breakEvenRate*s1.k_gold],type:'scatter',mode:'markers+text',text:['gold'],textposition:'top left',marker:{size:10,color:'#fbbf24'},name:fa?'قاعده طلایی':'Golden rule'}];
      const path=cm.transitionPath(s0.k_star,45);const trans=[{x:path.map(r=>r[0]),y:path.map(r=>100*r[1]/s1.k_star),type:'scatter',mode:'lines',name:'k',line:blue},{x:path.map(r=>r[0]),y:path.map(r=>100*r[2]/s1.y_star),type:'scatter',mode:'lines',name:'y',line:green},{x:path.map(r=>r[0]),y:path.map(r=>100*r[3]/s1.c_star),type:'scatter',mode:'lines',name:'c',line:amber}];
      return {metrics:[{label:'k*',value:num(s1.k_star,3),delta:delta(s1.k_star-s0.k_star,3)},{label:'y*',value:num(s1.y_star,3),delta:delta(s1.y_star-s0.y_star,3)},{label:'c*',value:num(s1.c_star,3),delta:delta(s1.c_star-s0.c_star,3)},{label:fa?'نرخ پس‌انداز طلایی':'Golden-rule s',value:pct(s1.s_gold)}],charts:[{title:fa?'وضعیت پایدار و قاعده طلایی':'Steady State & Golden Rule',data:steady,layout:commonLayout(lang,'k',fa?'مقدار به ازای نیروی کار مؤثر':'Per-effective-worker amount')},{title:fa?'مسیر گذار':'Transition Path',data:trans,layout:commonLayout(lang,fa?'دوره':'Period',fa?'شاخص (وضعیت جدید=۱۰۰)':'Index (new SS=100)')}],analysis:fa?`سرمایه وضعیت پایدار ${num(s1.k_star,3)} و تولید پایدار ${num(s1.y_star,3)} است. تغییر نرخ پس‌انداز سطح k* و y* را جابه‌جا می‌کند، اما در مدل پایه نرخ رشد بلندمدت به ازای نیروی کار مؤثر از پیشرفت فناوری می‌آید.`:`Steady-state capital is ${num(s1.k_star,3)} and output is ${num(s1.y_star,3)}. A saving-rate change shifts steady-state levels; in the baseline Solow model long-run growth per effective worker comes from technology.`,formula:`y = A k^α\ns y = (δ+n+g)k\nk* = [sA/(δ+n+g)]^(1/(1−α))`,table:{columns:['Variable','Baseline','Current','Change'],rows:[['k*',s0.k_star,s1.k_star,s1.k_star-s0.k_star],['y*',s0.y_star,s1.y_star,s1.y_star-s0.y_star],['c*',s0.c_star,s1.c_star,s1.c_star-s0.c_star],['k golden',s0.k_gold,s1.k_gold,s1.k_gold-s0.k_gold]]}};
    }

    if (id === 'taylor') {
      const make=(v:ModelState)=>new TaylorRuleModel({neutralRealRate:n(v.neutral),inflationTarget:n(v.target),inflationResponse:n(v.aPi),outputGapResponse:n(v.aY)});const bm=make(base),cm=make(current);const i0=bm.policyRate(n(base.inflation),n(base.gap)),i1=cm.policyRate(n(current.inflation),n(current.gap));const grid=linspace(-.02,.12,220);const data=[{x:grid.map(v=>v*100),y:grid.map(v=>100*bm.policyRate(v,n(base.gap))),type:'scatter',mode:'lines',name:fa?'مبنا':'Baseline',line:baseLine},{x:grid.map(v=>v*100),y:grid.map(v=>100*cm.policyRate(v,n(current.gap))),type:'scatter',mode:'lines',name:fa?'قاعده تیلور':'Taylor rule',line:blue},{x:[100*n(current.target),100*n(current.target)],y:[-5,25],type:'scatter',mode:'lines',name:fa?'هدف تورمی':'Inflation target',line:{color:'#34d399',dash:'dash'}},{x:[100*n(base.inflation),100*n(current.inflation)],y:[100*i0,100*i1],type:'scatter',mode:'markers+text',text:['E₀','E₁'],textposition:'top right',marker:{size:[9,12],color:['#94a3b8','#f8fafc']},name:fa?'وضعیت':'State'}];
      return {metrics:[{label:'i*',value:pct(i1),delta:pp(i1-i0)},{label:'π',value:pct(n(current.inflation)),delta:pp(n(current.inflation)-n(base.inflation))},{label:fa?'شکاف تولید':'Output gap',value:pct(n(current.gap)),delta:pp(n(current.gap)-n(base.gap))},{label:fa?'نرخ حقیقی فیشر':'Fisher real rate',value:pct(cm.fisherRealRate(i1,n(current.inflation)))}],charts:[{title:fa?'واکنش نرخ سیاستی به تورم':'Policy-Rate Response to Inflation',data,layout:commonLayout(lang,fa?'تورم (%)':'Inflation (%)',fa?'نرخ سیاستی (%)':'Policy rate (%)')}],analysis:fa?`قاعده تیلور برای پارامترهای جاری نرخ اسمی ${pct(i1)} را پیشنهاد می‌کند. فاصله تورم از هدف و شکاف تولید با ضرایب aπ=${n(current.aPi).toFixed(2)} و ay=${n(current.aY).toFixed(2)} وارد واکنش سیاستی می‌شوند.`:`The current Taylor rule implies a nominal policy rate of ${pct(i1)}. Inflation deviations and the output gap enter with coefficients aπ=${n(current.aPi).toFixed(2)} and ay=${n(current.aY).toFixed(2)}.`,formula:`i = r* + π + aπ(π−π*) + ay·gap\nr_real ≈ i − πᵉ`,table:{columns:['Variable','Baseline','Current','Change'],rows:[['Policy rate',i0,i1,i1-i0],['Inflation',n(base.inflation),n(current.inflation),n(current.inflation)-n(base.inflation)],['Output gap',n(base.gap),n(current.gap),n(current.gap)-n(base.gap)]]}};
    }

    if (id === 'labor') {
      const make=(v:ModelState)=>new LaborMarketModel({productivity:n(v.productivity),markup:n(v.markup),wagePressure:n(v.wagePressure),wageSensitivity:n(v.wageSensitivity),okunBeta:n(v.okunBeta),outputGap:n(v.outputGap),laborForce:n(v.laborForce)});const bm=make(base),cm=make(current),s0=bm.solve(),s1=cm.solve();const umax=Math.min(.35,Math.max(.16,s0.u,s1.u,s0.u_n,s1.u_n)+.03),u=linspace(0,umax,260),gaps=linspace(-.1,.1,240);
      const wsps=[{x:u.map(x=>x*100),y:u.map(x=>bm.wageSettingWage(x)),type:'scatter',mode:'lines',name:fa?'WS مبنا':'Baseline WS',line:baseLine},{x:u.map(x=>x*100),y:u.map(()=>bm.priceSettingWage),type:'scatter',mode:'lines',name:fa?'PS مبنا':'Baseline PS',line:{...baseLine,dash:'dash'}},{x:u.map(x=>x*100),y:u.map(x=>cm.wageSettingWage(x)),type:'scatter',mode:'lines',name:'WS',line:blue},{x:u.map(x=>x*100),y:u.map(()=>cm.priceSettingWage),type:'scatter',mode:'lines',name:'PS',line:red},{x:[s1.u_n*100],y:[cm.priceSettingWage],type:'scatter',mode:'markers+text',text:['uₙ'],textposition:'top right',marker:{size:12,color:'#f8fafc'},name:'uₙ'}];
      const okun=[{x:gaps.map(g=>g*100),y:gaps.map(g=>100*(cm.naturalUnemployment-cm.okunBeta*g)),type:'scatter',mode:'lines',name:fa?'رابطه اوکان':'Okun relation',line:green},{x:[n(current.outputGap)*100],y:[s1.u*100],type:'scatter',mode:'markers+text',text:['E₁'],textposition:'top right',marker:{size:12,color:'#f8fafc'},name:'E₁'}];
      return {metrics:[{label:'uₙ',value:pct(s1.u_n),delta:pp(s1.u_n-s0.u_n)},{label:'u',value:pct(s1.u),delta:pp(s1.u-s0.u)},{label:fa?'اشتغال':'Employment',value:num(s1.employment,1),delta:delta(s1.employment-s0.employment,1)},{label:'W/P (PS)',value:num(s1.real_wage_ps,3),delta:delta(s1.real_wage_ps-s0.real_wage_ps,3)}],charts:[{title:'WS–PS',data:wsps,layout:commonLayout(lang,fa?'بیکاری (%)':'Unemployment (%)',fa?'دستمزد حقیقی / بهره‌وری':'Real wage / productivity')},{title:fa?'قانون اوکان':'Okun’s Law',data:okun,layout:commonLayout(lang,fa?'شکاف تولید (%)':'Output gap (%)',fa?'بیکاری (%)':'Unemployment (%)')}],analysis:fa?`نرخ بیکاری طبیعی ${pct(s1.u_n)} و بیکاری جاری ${pct(s1.u)} است. مارک‌آپ و فشار دستمزدی نرخ طبیعی را جابه‌جا می‌کنند؛ شکاف تولید از طریق قانون اوکان جزء ادواری بیکاری را تغییر می‌دهد.`:`Natural unemployment is ${pct(s1.u_n)} and current unemployment is ${pct(s1.u)}. Markup and wage pressure shift the natural rate; the output gap changes cyclical unemployment through Okun’s law.`,formula:`WS: w = A(1+z−βu·u)\nPS: w = A/(1+μ)\nu = uₙ − β_Okun·output_gap`,table:{columns:['Variable','Baseline','Current','Change'],rows:[['Natural unemployment',s0.u_n,s1.u_n,s1.u_n-s0.u_n],['Actual unemployment',s0.u,s1.u,s1.u-s0.u],['Employment',s0.employment,s1.employment,s1.employment-s0.employment],['Real wage PS',s0.real_wage_ps,s1.real_wage_ps,s1.real_wage_ps-s0.real_wage_ps]]}};
    }

    if (id === 'phillips') {
      const make=(v:ModelState)=>new ExpectationsPhillipsModel({expectedInflation:n(v.expectedInflation),unemployment:n(v.unemployment),naturalUnemployment:n(v.naturalUnemployment),alpha:n(v.alpha),supplyShock:n(v.supplyShock)});const bm=make(base),cm=make(current),s0=bm.solve(),s1=cm.solve();const maxU=Math.min(.30,Math.max(.14,s0.unemployment,s1.unemployment,s0.natural_unemployment,s1.natural_unemployment)+.03),u=linspace(0,maxU,280);
      const curve=[{x:u.map(v=>v*100),y:u.map(v=>100*bm.inflation(v)),type:'scatter',mode:'lines',name:fa?'SRPC مبنا':'Baseline SRPC',line:baseLine},{x:u.map(v=>v*100),y:u.map(v=>100*cm.inflation(v)),type:'scatter',mode:'lines',name:'SRPC',line:red},{x:[s1.natural_unemployment*100,s1.natural_unemployment*100],y:[-10,20],type:'scatter',mode:'lines',name:'LRPC',line:{color:'#38bdf8',dash:'dash'}},{x:[s0.unemployment*100,s1.unemployment*100],y:[s0.inflation*100,s1.inflation*100],type:'scatter',mode:'markers+text',text:['E₀','E₁'],textposition:'top right',marker:{size:[9,12],color:['#94a3b8','#f8fafc']},name:fa?'تعادل':'State'}];
      const decomp=[{x:[fa?'انتظارات':'Expected',fa?'شکاف بیکاری':'U-gap',fa?'شوک عرضه':'Supply shock',fa?'تورم نهایی':'Final'],y:[s1.expected_inflation*100,s1.cyclical_component*100,s1.supply_shock*100,s1.inflation*100],type:'bar',marker:{color:['#38bdf8','#34d399','#fb7185','#fbbf24']},name:fa?'اجزا':'Components'}];
      return {metrics:[{label:'π',value:pct(s1.inflation),delta:pp(s1.inflation-s0.inflation)},{label:'πᵉ',value:pct(s1.expected_inflation),delta:pp(s1.expected_inflation-s0.expected_inflation)},{label:'u−uₙ',value:`${(100*s1.unemployment_gap).toFixed(2)} pp`},{label:fa?'شوک عرضه':'Supply shock',value:pct(s1.supply_shock),delta:pp(s1.supply_shock-s0.supply_shock)}],charts:[{title:fa?'منحنی فیلیپس انتظارات‌افزوده':'Expectations-Augmented Phillips Curve',data:curve,layout:commonLayout(lang,fa?'بیکاری (%)':'Unemployment (%)',fa?'تورم (%)':'Inflation (%)')},{title:fa?'تجزیه تورم':'Inflation Decomposition',data:decomp,layout:commonLayout(lang,'',fa?'واحد درصد':'Percentage points')}],analysis:fa?`تورم جاری ${pct(s1.inflation)} است: تورم مورد انتظار ${pct(s1.expected_inflation)}، اثر شکاف بیکاری ${(100*s1.cyclical_component).toFixed(2)} واحد درصد و شوک عرضه ${(100*s1.supply_shock).toFixed(2)} واحد درصد.`:`Current inflation is ${pct(s1.inflation)}: expected inflation ${pct(s1.expected_inflation)}, unemployment-gap effect ${(100*s1.cyclical_component).toFixed(2)} pp, and supply shock ${(100*s1.supply_shock).toFixed(2)} pp.`,formula:`π = πᵉ − α(u−uₙ) + v`,table:{columns:['Component','Baseline','Current','Change'],rows:[['Inflation',s0.inflation,s1.inflation,s1.inflation-s0.inflation],['Expected inflation',s0.expected_inflation,s1.expected_inflation,s1.expected_inflation-s0.expected_inflation],['Unemployment',s0.unemployment,s1.unemployment,s1.unemployment-s0.unemployment],['Natural unemployment',s0.natural_unemployment,s1.natural_unemployment,s1.natural_unemployment-s0.natural_unemployment]]}};
    }

    if (id === 'fiscal') {
      const make=(v:ModelState)=>new FiscalDebtModel({initialDebtRatio:n(v.initialDebtRatio),interestRate:n(v.interestRate),growthRate:n(v.growthRate),primaryBalance:n(v.primaryBalance),years:n(v.years)});const bm=make(base),cm=make(current),s0=bm.solve(),s1=cm.solve(),p0=bm.path(),p1=cm.path();
      const debt=[{x:p0.map(r=>r[0]),y:p0.map(r=>r[1]*100),type:'scatter',mode:'lines',name:fa?'مبنا':'Baseline',line:baseLine},{x:p1.map(r=>r[0]),y:p1.map(r=>r[1]*100),type:'scatter',mode:'lines',name:fa?'جاری':'Current',line:blue}];
      const balance=[{x:p1.map(r=>r[0]),y:p1.map(r=>r[2]*100),type:'scatter',mode:'lines',name:fa?'پرداخت بهره':'Interest bill',line:red},{x:p1.map(r=>r[0]),y:p1.map(r=>r[3]*100),type:'scatter',mode:'lines',name:fa?'تراز تثبیت‌کننده':'Stabilizing PB',line:green},{x:[0,n(current.years)],y:[n(current.primaryBalance)*100,n(current.primaryBalance)*100],type:'scatter',mode:'lines',name:fa?'تراز اولیه انتخابی':'Selected PB',line:amber}];
      return {metrics:[{label:fa?'بدهی فعلی/GDP':'Debt/GDP now',value:pct(n(current.initialDebtRatio),1),delta:pp(n(current.initialDebtRatio)-n(base.initialDebtRatio),1)},{label:fa?'بدهی نهایی/GDP':'Final Debt/GDP',value:pct(s1.final_debt_ratio,1),delta:pp(s1.final_debt_ratio-s0.final_debt_ratio,1)},{label:'r−g',value:`${(100*s1.r_minus_g).toFixed(2)} pp`,delta:pp(s1.r_minus_g-s0.r_minus_g)},{label:fa?'تراز اولیه تثبیت‌کننده':'Stabilizing PB',value:pct(s1.stabilizing_primary_balance)}],charts:[{title:fa?'مسیر بدهی دولت':'Government Debt Path',data:debt,layout:commonLayout(lang,fa?'سال':'Year','Debt/GDP (%)')},{title:fa?'فشار بهره و تراز تثبیت‌کننده':'Interest Burden & Stabilizing Balance',data:balance,layout:commonLayout(lang,fa?'سال':'Year','% GDP')}],analysis:fa?`با r−g برابر ${(100*s1.r_minus_g).toFixed(2)} واحد درصد، عامل snowball برابر ${s1.snowball_factor.toFixed(4)} است. در افق ${n(current.years)} سال نسبت بدهی به ${pct(s1.final_debt_ratio,1)} می‌رسد. تراز اولیه تثبیت‌کننده در نقطه شروع ${pct(s1.stabilizing_primary_balance)} GDP است.`:`With r−g at ${(100*s1.r_minus_g).toFixed(2)} pp, the snowball factor is ${s1.snowball_factor.toFixed(4)}. Over ${n(current.years)} years debt reaches ${pct(s1.final_debt_ratio,1)} of GDP. The initial stabilizing primary balance is ${pct(s1.stabilizing_primary_balance)} of GDP.`,formula:`bₜ = [(1+r)/(1+g)] bₜ₋₁ − pb\npb_stabilize = {[(1+r)/(1+g)]−1}·b`,table:{columns:[fa?'سال':'Year','Debt/GDP','Interest/GDP','Stabilizing PB'],rows:p1.map(r=>[r[0],r[1]*100,r[2]*100,r[3]*100])}};
    }

    if (id === 'transmission') {
      const make=(v:ModelState)=>new MonetaryTransmissionModel({policyShock:n(v.policyShock),passThrough:n(v.passThrough),policyPersistence:n(v.policyPersistence),outputPersistence:n(v.outputPersistence),demandSensitivity:n(v.demandSensitivity),inflationPersistence:n(v.inflationPersistence),phillipsSlope:n(v.phillipsSlope),investmentSensitivity:n(v.investmentSensitivity),consumptionSensitivity:n(v.consumptionSensitivity),quarters:n(v.quarters)});const bm=make(base),cm=make(current),s0=bm.solve(),s1=cm.solve(),p=cm.path();
      const q=p.map(r=>r[0]);const rates=[{x:q,y:p.map(r=>r[1]),type:'scatter',mode:'lines',name:fa?'شکاف نرخ سیاستی':'Policy rate gap',line:blue},{x:q,y:p.map(r=>r[2]),type:'scatter',mode:'lines',name:fa?'شکاف نرخ بازار':'Market rate gap',line:amber}];const macro=[{x:q,y:p.map(r=>r[3]),type:'scatter',mode:'lines',name:fa?'شکاف تولید':'Output gap',line:red},{x:q,y:p.map(r=>r[4]),type:'scatter',mode:'lines',name:fa?'انحراف تورم':'Inflation gap',line:green}];const spend=[{x:q,y:p.map(r=>r[5]),type:'scatter',mode:'lines',name:fa?'سرمایه‌گذاری':'Investment',line:blue},{x:q,y:p.map(r=>r[6]),type:'scatter',mode:'lines',name:fa?'مصرف':'Consumption',line:amber}];
      return {metrics:[{label:fa?'اوج شکاف نرخ بازار':'Peak market-rate gap',value:`${s1.peak_market_rate_gap_pp.toFixed(2)} pp`},{label:fa?'اوج شکاف تولید':'Peak output gap',value:`${s1.peak_output_gap_pct.toFixed(2)}%`,delta:`Q${s1.peak_output_quarter}`},{label:fa?'اوج انحراف تورم':'Peak inflation gap',value:`${s1.peak_inflation_gap_pp.toFixed(2)} pp`,delta:`Q${s1.peak_inflation_quarter}`},{label:fa?'اوج انحراف سرمایه‌گذاری':'Peak investment deviation',value:`${s1.peak_investment_deviation_pct.toFixed(2)}%`}],charts:[{title:fa?'شوک نرخ و عبور به بازار':'Policy Shock & Pass-Through',data:rates,layout:commonLayout(lang,fa?'فصل پس از شوک':'Quarter after shock','pp')},{title:fa?'واکنش تولید و تورم':'Output & Inflation Response',data:macro,layout:commonLayout(lang,fa?'فصل پس از شوک':'Quarter after shock',fa?'درصد / واحد درصد':'% / pp')},{title:fa?'واکنش مخارج':'Spending Response',data:spend,layout:commonLayout(lang,fa?'فصل پس از شوک':'Quarter after shock',fa?'درصد انحراف':'% deviation')}],analysis:fa?`این مدل آموزشی پویایی با وقفه را نشان می‌دهد. شوک سیاستی ${pct(n(current.policyShock))} ابتدا با ضریب عبور ${n(current.passThrough).toFixed(2)} به نرخ بازار می‌رسد؛ اوج واکنش تولید در فصل ${s1.peak_output_quarter} و اوج واکنش تورم در فصل ${s1.peak_inflation_quarter} رخ می‌دهد.`:`This pedagogical dynamic model emphasizes lags. A ${pct(n(current.policyShock))} policy shock passes to the market rate with coefficient ${n(current.passThrough).toFixed(2)}; the output response peaks in quarter ${s1.peak_output_quarter} and inflation in quarter ${s1.peak_inflation_quarter}.`,formula:`i_gap,t = ρᵢ i_gap,t−1\nr_m,t = φ i_gap,t\nxₜ = ρₓxₜ₋₁ − σ r_m,t−1\nπ_gap,t = ρπ π_gap,t−1 + κxₜ₋₁`,table:{columns:['Quarter','Policy gap (pp)','Market gap (pp)','Output gap (%)','Inflation gap (pp)','Investment dev (%)','Consumption dev (%)'],rows:p}};
    }

    if (id === 'policy') {
      const result=runPolicyScenario(s(current.scenario) as any,n(current.intensity),s(current.exchangeRegime) as any);
      const rows=[
        [fa?'IS–LM: تولید':'IS–LM: output',result.islm.base.Y,result.islm.current.Y,result.islm.current.Y-result.islm.base.Y],
        [fa?'IS–LM: نرخ بهره (pp)':'IS–LM: interest rate (pp)',result.islm.base.r*100,result.islm.current.r*100,(result.islm.current.r-result.islm.base.r)*100],
        [fa?'AD–AS: تولید':'AD–AS: output',result.adas.base.Y,result.adas.current.Y,result.adas.current.Y-result.adas.base.Y],
        [fa?'AD–AS: تورم (pp)':'AD–AS: inflation (pp)',result.adas.base.Inflation,result.adas.current.Inflation,result.adas.current.Inflation-result.adas.base.Inflation],
        [fa?'بیکاری (pp)':'Unemployment (pp)',result.labor.base.u*100,result.labor.current.u*100,(result.labor.current.u-result.labor.base.u)*100],
        [fa?'اقتصاد باز: تولید':'Open economy: output',result.open.base.Y,result.open.current.Y,result.open.current.Y-result.open.base.Y],
        [fa?'نرخ ارز e':'Exchange rate e',result.open.base.e,result.open.current.e,result.open.current.e-result.open.base.e],
        [fa?'سولو: y*':'Solow: y*',result.solow.base.y_star,result.solow.current.y_star,result.solow.current.y_star-result.solow.base.y_star],
        [fa?'بدهی نهایی (%GDP)':'Final debt (%GDP)',result.fiscal.base.final_debt_ratio*100,result.fiscal.current.final_debt_ratio*100,(result.fiscal.current.final_debt_ratio-result.fiscal.base.final_debt_ratio)*100],
        [fa?'تیلور: نرخ سیاستی (pp)':'Taylor policy rate (pp)',result.taylor.baseRate*100,result.taylor.currentRate*100,(result.taylor.currentRate-result.taylor.baseRate)*100],
        [fa?'انتقال: اوج شکاف تولید (%)':'Transmission peak output gap (%)',result.transmission.base.peak_output_gap_pct,result.transmission.current.peak_output_gap_pct,result.transmission.current.peak_output_gap_pct-result.transmission.base.peak_output_gap_pct]
      ];
      const short=rows.slice(0,6);const data=[{x:short.map(r=>r[0]),y:short.map(r=>r[3]),type:'bar',marker:{color:short.map(r=>Number(r[3])>=0?'#34d399':'#fb7185')},name:fa?'تغییر نسبت به مبنا':'Change vs baseline'}];
      return {metrics:[{label:fa?'IS–LM: ΔY':'IS–LM: ΔY',value:delta(result.islm.current.Y-result.islm.base.Y,1)},{label:fa?'AD–AS: ΔY':'AD–AS: ΔY',value:delta(result.adas.current.Y-result.adas.base.Y,1)},{label:fa?'Δ نرخ سیاستی':'Δ policy rate',value:pp(result.taylor.currentRate-result.taylor.baseRate)},{label:fa?'بدهی نهایی':'Final debt',value:pct(result.fiscal.current.final_debt_ratio,1)}],charts:[{title:fa?'خلاصه اثرات بین‌مدلی':'Cross-Model Impact Summary',data,layout:{...commonLayout(lang,'',fa?'تغییر':'Change'),xaxis:{tickangle:-18,gridcolor:'rgba(148,163,184,.1)'}}}],analysis:fa?`این آزمایشگاه یک مدل ساختاری واحد نیست؛ چند چارچوب آموزشی را با نگاشت‌های شفاف به هم متصل می‌کند. شدت شوک ${result.intensity.toFixed(2)} است. تغییر IS–LM در تولید ${delta(result.islm.current.Y-result.islm.base.Y,1)} واحد و تغییر نرخ پیشنهادی تیلور ${pp(result.taylor.currentRate-result.taylor.baseRate)} است. نتایج بین‌مدلی را باید با توجه به فرض‌های پل‌زننده تفسیر کرد.`:`This lab is not one estimated structural model; it connects distinct teaching frameworks through explicit bridge assumptions. Shock intensity is ${result.intensity.toFixed(2)}. IS–LM output changes by ${delta(result.islm.current.Y-result.islm.base.Y,1)} and the Taylor-implied policy rate by ${pp(result.taylor.currentRate-result.taylor.baseRate)}. Interpret cross-model results with the bridge assumptions in mind.`,formula:fa?'پل‌ها: شکاف تولید AD–AS → اوکان → بیکاری → فیلیپس؛ تورم/شکاف تولید → قاعده تیلور → انتقال پولی.':'Bridges: AD–AS output gap → Okun → unemployment → Phillips; inflation/output gap → Taylor rule → transmission.',table:{columns:[fa?'بلوک':'Block',fa?'مبنا':'Baseline',fa?'سناریو':'Scenario',fa?'تغییر':'Change'],rows}};
    }

    throw new Error(`Unknown model id: ${id}`);
  } catch (err:any) {
    return {metrics:[],charts:[],analysis:fa?'پارامترهای انتخاب‌شده خارج از دامنه معتبر مدل هستند.':'Selected parameters are outside the valid model range.',formula:'',table:{columns:[],rows:[]},warning:err?.message || String(err)};
  }
}
